### Examen T2 - Manipulación de Arrays

**Pregunta 1:** Dado un array numpy unidimensional de tamaño 10, redimensiona este array a una matriz de tamaño 5x2.

array --> [45,23,6,7,4,9,25,14,47,66]

resultado:

[45  9]

[23 25]

[ 6 14]

[ 7 47]

[ 4 66]

In [5]:
import numpy as np
a=np.array([45,23,6,7,4,9,25,14,47,66])
a1=np.reshape(a,(5,2),order="F")
print(a)
print(a1)

[45 23  6  7  4  9 25 14 47 66]
[[45  9]
 [23 25]
 [ 6 14]
 [ 7 47]
 [ 4 66]]


**Pregunta 2:** Dado un array numpy bidimensional de tamaño 3x4, redimensiona este array a un vector unidimensional.

array -->
 
[45,23,6,33]

[10,3,44,28]

[28,72,52,22]

Resultado -->  [45 10 28 23  3 72  6 44 52 33 28 22]
 

In [12]:
b=np.array([[45,23,6,33],[10,3,44,28],[28,72,52,22]])
print(b)
b1=b.flatten(order="F")
print(b1)


[[45 23  6 33]
 [10  3 44 28]
 [28 72 52 22]]
[45 10 28 23  3 72  6 44 52 33 28 22]


**Pregunta 3:** Generar un array unidimensional con 24 elementos aleatorios a continuación:

* Redimiensionar a un array bidimensional de tamaño 4x6 
* Redimensionar a partir del anterior a un array tridimensional de tamaño 2x3x4.

In [21]:
print("array unidimensional con 24 elementos aleatorios:")
c=np.random.randint(0,101,size=24)
print(c)
print("redimensionamiento a 4x6:")
c1=np.reshape(c,(4,6))
print(c1)
print("redimensionamiento el anterior a array tridimensional de 2x3x4:")
c2=np.reshape(c1,(2,3,4))
print(c2)



array unidimensional con 24 elementos aleatorios:
[  9  79  37  64  98  42  41 100  85  29  76  79  79  80  42  71  38  94
   7  70  91  95  75   7]
redimensionamiento a 4x6:
[[  9  79  37  64  98  42]
 [ 41 100  85  29  76  79]
 [ 79  80  42  71  38  94]
 [  7  70  91  95  75   7]]
redimensionamiento el anterior a array tridimensional de 2x3x4:
[[[  9  79  37  64]
  [ 98  42  41 100]
  [ 85  29  76  79]]

 [[ 79  80  42  71]
  [ 38  94   7  70]
  [ 91  95  75   7]]]


**Pregunta 4:** Dado un array numpy bidimensional A de tamaño 3x3 y un array numpy bidimensional B de tamaño 3x2, crea un nuevo array que sea la concatenación horizontal de A y B.

In [33]:
print("Array bidimensional de 3x3: ")
A=np.random.randint(0,101,size=(3,3))
print(A)
print("Array bidimensional de 3x2: ")
B=np.random.randint(0,101,size=(3,2))
print(B)
print("Nuevo array, concatenación horizontal de A y B:")
C=np.concatenate((A,B),axis=1)
print(C)

Array bidimensional de 3x3: 
[[80 91 72]
 [22 17 21]
 [89 72 29]]
Array bidimensional de 3x2: 
[[59 39]
 [44 54]
 [66 26]]
Nuevo array, concatenación horizontal de A y B:
[[80 91 72 59 39]
 [22 17 21 44 54]
 [89 72 29 66 26]]


**Pregunta 5:** Dado un array numpy bidimensional A de tamaño 4x4, divide este array en dos arrays, uno que contenga las dos primeras filas y otro que contenga las dos últimas filas.

In [35]:
print("Array bidimensional de 4x4: ")
A=np.random.randint(0,101,size=(4,4))
print(A)
print("división del array en dos:")
B=np.split(A,2)
print(B)

Array bidimensional de 4x4: 
[[ 31  19  90  85]
 [ 38   3  77  75]
 [  9  65  60  84]
 [ 99  43 100  74]]
división del array en dos:
[array([[31, 19, 90, 85],
       [38,  3, 77, 75]]), array([[  9,  65,  60,  84],
       [ 99,  43, 100,  74]])]


**Pregunta 6:** Dado un array numpy unidimensional de tamaño 10, inserta un nuevo elemento en la posición 5 y elimina el elemento en la posición 3.

In [38]:
print("Array unidimensional de 10 elementos: ")
A=np.random.randint(0,101,size=10)
print(A)
B=np.insert(A,5,34)
print(B)
C=np.delete(B,3)
print(C)

Array unidimensional de 10 elementos: 
[58 29 71  4 42 41 23 57 90 63]
[58 29 71  4 42 34 41 23 57 90 63]
[58 29 71 42 34 41 23 57 90 63]


Una forma sencilla de filtrar valores dentro de un array es pasando un array de valores booleanos, veamos:


In [1]:
import numpy as np 

a = np.array([5,2,4,7,8])
filtrado = a[[True,False,True,False,True]]
print(filtrado)

[5 4 8]


**Pregunta 7:** Basandose en el ejemplo anterior y los conocimientos sobre operadores de relación generar un array  unidimensional de tamaño 15 y elementos aleatorios, elimina todos los elementos que sean mayores que 10 y luego inserta el valor 20 al final del array resultante.

In [44]:
print("Array unidimensional de 15 elementos aleatorios:")
A=np.random.randint(0,20,size=15)
print(A)
print("Se eliminan todos aquellos elementos que sean mayores a 10:")
B=A[A<10]
print(B)
print("Se inserta el valor 20 al final del array resultante:")
C=np.append(B,20)
print(C)

Array unidimensional de 15 elementos aleatorios:
[19 11  2  4  0 17 12 15 13  5 14 10  7  0  7]
Se eliminan todos aquellos elementos que sean mayores a 10:
[2 4 0 5 7 0 7]
Se inserta el valor 20 al final del array resultante:
[ 2  4  0  5  7  0  7 20]


**Pregunta 8:** Dado un array numpy bidimensional de tamaño 3x3, calcula la matriz transpuesta y la matriz inversa.

In [45]:
import numpy.linalg as la
print("Array bidimensional de 3x3: ")
A=np.random.randint(0,101,size=(3,3))
print(A)
print("matriz transpuesta:")
print(A.T)
print("matriz inversa:")
print(la.inv(A))

Array bidimensional de 3x3: 
[[82 25 42]
 [20 57 71]
 [66 96 69]]
matriz transpuesta:
[[82 20 66]
 [25 57 96]
 [42 71 69]]
matriz inversa:
[[ 0.01247404 -0.00998183  0.00267826]
 [-0.01430426 -0.01248702  0.0215559 ]
 [ 0.00796989  0.02692108 -0.01805988]]


**Pregunta 9:** Dadas dos matrices numpy A y B de tamaño 3x3, calcula el producto matricial de A y B.

In [46]:
print("Array bidimensional de 3x3: ")
A=np.random.randint(0,101,size=(3,3))
print(A)
print("Array bidimensional de 3x3: ")
B=np.random.randint(0,101,size=(3,3))
print(B)
mult=np.multiply(A,B)
print(mult)

Array bidimensional de 3x3: 
[[42 36 53]
 [66 60  0]
 [52 72 59]]
Array bidimensional de 3x3: 
[[15 89 60]
 [58 96 15]
 [10 72 87]]
[[ 630 3204 3180]
 [3828 5760    0]
 [ 520 5184 5133]]


**Pregunta 10:** Dado un array numpy bidimensional de tamaño 3x3, calcula la suma de los elementos en cada fila y la media de los elementos en cada columna.

In [48]:
print("Array bidimensional de 3x3: ")
A=np.random.randint(0,101,size=(3,3))
print(A)
print("suma de los elementos de cada fila:")
B=np.sum(A,axis=1)
print(B)
print("media de los elementos en cada columna:")
C=np.mean(A,axis=0)
print(C)


Array bidimensional de 3x3: 
[[38 79 56]
 [20 60 91]
 [92 64 51]]
suma de los elementos de cada fila:
[173 171 207]
media de los elementos en cada columna:
[50.         67.66666667 66.        ]


**Pregunta 11:** Dado un array numpy unidimensional de tamaño 10, calcula el producto acumulativo de los elementos del array y luego encuentra el índice del elemento máximo en el array resultante.

In [58]:
print("Array unidimensional:")
d=np.random.randint(1,11,size=15)
print(d)
producto_acumulativo = np.cumprod(d)
print("Producto acumulativo de los elementos:")
print(producto_acumulativo)
indice_maximo = np.argmax(producto_acumulativo)
print("Índice del elemento máximo en el array resultante:", indice_maximo)

Array unidimensional:
[ 3  5  4  4  1 10  7  5  5  9  1  9  3  3  2]
Producto acumulativo de los elementos:
[        3        15        60       240       240      2400     16800
     84000    420000   3780000   3780000  34020000 102060000 306180000
 612360000]
Índice del elemento máximo en el array resultante: 14


**Pregunta 12:** Dado un array numpy unidimensional que representa las calificaciones de los estudiantes en un examen, calcula la media, la mediana y la desviación estándar de las calificaciones.

In [62]:
print("Array unidimensional de las calificaciones de estudiantes:")
d=np.random.randint(3,11,size=23)
print(d)
print("La media: ", np.mean(d))
print("La mediana: ", np.median(d))
print("La desviación estándar: ", np.std(d))

Array unidimensional de las calificaciones de estudiantes:
[10  4  5  9  7  4  9  5  8  6  7  9  8  8  9  4  8 10  4  7  8  5 10]
La media:  7.130434782608695
La mediana:  8.0
La desviación estándar:  2.0494823911987257


**Pregunta 13:** Dado un array numpy bidimensional que representa las edades de los estudiantes en una clase (filas representan diferentes grupos de edad y columnas representan diferentes géneros), calcula la moda de las edades en cada grupo de edad y género.

In [69]:
edades = np.array([[20, 22, 24],
                   [21, 23, 20]])

print("Array bidimensional de edades:")
print(edades)

# Calcula la moda de las edades para cada grupo de edad (a lo largo de las filas)
moda_por_grupo_de_edad = np.apply_along_axis(lambda x: np.bincount(x).argmax(), axis=1, arr=edades)

print("Moda de las edades para cada grupo de edad:")
print(moda_por_grupo_de_edad)

# Calcula la moda de las edades para cada género (a lo largo de las columnas)
moda_por_genero = np.apply_along_axis(lambda x: np.bincount(x).argmax(), axis=0, arr=edades)

print("Moda de las edades para cada género:")
print(moda_por_genero)


Array bidimensional de edades:
[[20 22 24]
 [21 23 20]]
Moda de las edades para cada grupo de edad:
[20 20]
Moda de las edades para cada género:
[20 22 20]



**Pregunta 14:** Un investigador está estudiando el rendimiento académico de un grupo de estudiantes en dos asignaturas: Matemáticas y Ciencias. Ha recopilado las calificaciones finales de los estudiantes en ambas asignaturas y quiere obtener algunas estadísticas descriptivas.

El array de calificaciones está estructurado de la siguiente manera:

* La primera columna representa las calificaciones de los estudiantes en Matemáticas.
* La segunda columna representa las calificaciones de los estudiantes en Ciencias.
* La segunda columna representa las calificaciones de los estudiantes en Ciencias.

Por cada asignatura calcule media, mediana y desviación estandar. Y saque sus conclusiones respecto al rendimiento.


[85, 90,65]

[70, 75,45]

[90, 85,88]

[65, 80,68]

[75, 70,59]

In [75]:
calificaciones = np.array([[85,90,65],
                           [70,75,45],
                           [90,85,88],
                           [65,80,68],
                           [75,70,59]])

media=np.mean(calificaciones,axis=0)
print("media: ",media)
print("mediana: ", np.median(calificaciones, axis=0))
print("desviación típica: ",np.std(calificaciones,axis=0))

media:  [77. 80. 65.]
mediana:  [75. 80. 65.]
desviación típica:  [ 9.2736185   7.07106781 13.95707706]


Para la mediana con respecto a la media, vemos que siguen una distribución simétrica o relativamente simétrica incluso con la variación de 2 puntos en el caso de la asignatura de matemáticas. La mediana nos proporciona el valor medio cuando las calificaciones están ordenadas de menor a mayor, de ahí que en este caso coinciden los valores de la media con los de la mediana. La desviación estándar proporciona una medida de la dispersión de los datos con respecto a la media. Una desviación estándar alta indica que las calificaciones están más dispersas alrededor de la media, mientras que una desviación estándar baja indica que las calificaciones están más cerca de la media. La alta desviación estándar en la tercera asignatura sugiere que las calificaciones están más dispersas, lo que podría indicar que los estudiantes tienen diferentes niveles de rendimiento en esa asignatura en comparación con las otras dos.

#### Utilizando máscaras

**Pregunta 15:**  Dado un array numpy unidimensional de tamaño 10 que representa las ventas diarias de una tienda, encuentra todos los días en los que las ventas superaron los 100 dólares.

array ----> [85, 110, 90, 130, 95, 105, 120, 140, 75, 115]

In [85]:
import numpy.ma as ma
print("Ventas diarias de una tienda:")
ventas_diarias=np.array([85, 110, 90, 130, 95, 105, 120, 140, 75, 115])
print(A)
print("A continuación, los días en los que la ventas superan los 100 dólares:")
dias=ma.masked_where(ventas_diarias<100, ventas_diarias)
print(dias)


Ventas diarias de una tienda:
[ 85 110  90 130  95 105 120 140  75 115]
A continuación, los días en los que la ventas superan los 100 dólares:
[-- 110 -- 130 -- 105 120 140 -- 115]


**Pregunta 16:** Dada una matriz numpy bidimensional que representa los resultados de un examen (filas representan estudiantes y columnas representan preguntas), encuentra todos los estudiantes que respondieron correctamente a todas las preguntas.

Array

[1, 0, 1, 1]

[1, 1, 1, 0]

[1, 1, 1, 1]

[0, 0, 1, 1]

[1, 0, 0, 1]

In [86]:
matriz=[[1, 0, 1, 1],

        [1, 1, 1, 0],

        [1, 1, 1, 1],

        [0, 0, 1, 1],

        [1, 0, 0, 1]]

mx1=ma.masked_equal(matriz,0)
print(mx1)

[[1 -- 1 1]
 [1 1 1 --]
 [1 1 1 1]
 [-- -- 1 1]
 [1 -- -- 1]]


El estudiante que respondió correctamente a todas las preguntas fue el tercero.